LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE		:= libogremain

LOCAL_C_INCLUDES	:= $(LOCAL_PATH)/../ \
                       $(OGRE_ROOT)/OgreMain/include \
                       $(OGRE_ROOT)/Components/RTShaderSystem/include \
                       $(OGRE_ROOT)/RenderSystems/GLES2/include \
                       $(OGRE_ROOT)/RenderSystems/GLES2/src/GLSLES/include \
                       $(OGRE_ROOT)/RenderSystems/GLES2/include/Android \
                       $(OGRE_ROOT)/Plugins/ParticleFX/include \
                       $(FREEIMAGE_ROOT)/Source \
                       $(ZZIP_ROOT)

LOCAL_SRC_FILES		:= \
    $(OGRE_ROOT)/OgreMain/src/OgreAlignedAllocator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAnimable.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAnimation.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAnimationState.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAnimationTrack.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreArchiveManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreArchive.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAutoParamDataSource.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreAxisAlignedBox.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreBillboard.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreBillboardChain.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreBillboardParticleRenderer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreBillboardSet.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreBone.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCamera.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCodec.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreColourValue.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCommon.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDualQuaternion.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderQueueSortingGrouping.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositorInstance.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositorManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositor.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceBatchHW.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreConfigFile.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareUniformBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreControllerManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreConvexBody.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceBatchVTF.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositionTargetPass.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositionPass.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDataStream.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositionTechnique.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDDSCodec.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowCaster.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSkeletonInstance.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreProgressiveMeshGenerator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDefaultHardwareBufferManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDefaultSceneQueries.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDepthBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDistanceLodStrategy.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstancedEntity.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDynLib.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreDynLibManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreEdgeListBuilder.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreCompositorChain.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreEntity.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreException.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreExternalTextureSource.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreExternalTextureSourceManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreFileSystem.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreFreeImageCodec.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreFrustum.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderQueueInvocation.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareCounterBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreGpuProgram.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreGpuProgramManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreGpuProgramParams.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreGpuProgramUsage.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareBufferManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareIndexBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareOcclusionQuery.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwarePixelBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHardwareVertexBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHighLevelGpuProgram.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreHighLevelGpuProgramManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreImage.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreKeyFrame.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreLight.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreLodStrategy.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreLodStrategyManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreLog.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreLogManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreManualObject.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMaterial.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMaterialManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMaterialSerializer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMath.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMatrix3.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMatrix4.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMemoryAllocatedObject.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMemoryNedAlloc.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMemoryNedPooling.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMemoryTracker.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMesh.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMeshManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMeshSerializer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMeshSerializerImpl.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMovableObject.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreMovablePlane.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreNode.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreNumerics.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreOptimisedUtil.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreOptimisedUtilGeneral.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreOptimisedUtilSSE.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticle.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticleEmitter.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticleEmitterCommands.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticleIterator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticleSystem.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreParticleSystemManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePass.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePatchMesh.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePatchSurface.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePixelCountLodStrategy.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePixelFormat.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePlane.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePlatformInformation.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePolygon.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePose.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePrecompiledHeaders.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePredefinedControllers.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePrefabFactory.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreProfiler.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgrePVRTCCodec.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreQuaternion.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRectangle2D.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderQueue.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderSystem.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderSystemCapabilities.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderSystemCapabilitiesManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderTarget.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderTexture.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderToVertexBuffer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRenderWindow.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreResource.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreResourceBackgroundQueue.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreResourceGroupManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreResourceManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRibbonTrail.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRoot.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreRotationSpline.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSceneManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSceneManagerEnumerator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSceneNode.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSceneQuery.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreScriptCompiler.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreScriptLexer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreScriptParser.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreScriptTranslator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSearchOps.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSerializer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowCameraSetup.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowCameraSetupFocused.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowCameraSetupPSSM.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowTextureManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSimpleRenderable.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSimpleSpline.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSkeleton.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSkeletonManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSkeletonSerializer.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreStaticGeometry.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreStreamSerialiser.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreString.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreStringConverter.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreStringInterface.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSubEntity.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSubMesh.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTagPoint.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTangentSpaceCalc.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTechnique.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTexture.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTextureManager.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreTextureUnitState.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreUserObjectBindings.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreUTFString.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreVector2.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreVector3.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreVector4.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreVertexIndexData.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceBatchShader.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceBatch.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreViewport.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreWindowEventUtilities.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreWireBoundingBox.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreWorkQueue.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreQueuedProgressiveMeshGenerator.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstanceBatchHW_VTF.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreZip.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreSmallVector.cpp \
	$(OGRE_ROOT)/OgreMain/src/OgreInstancedGeometry.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreTimer.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreConfigDialog.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreErrorDialog.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreAndroidLogListener.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreAPKZipArchive.cpp \
	$(OGRE_ROOT)/OgreMain/src/Android/OgreAPKFileSystemArchive.cpp \
	$(OGRE_ROOT)/OgreMain/src/Threading/OgreDefaultWorkQueueStandard.cpp \

LOCAL_CFLAGS		:= -DFREEIMAGE_LIB=1 -DOGRE_NONCLIENT_BUILD=1
#LOCAL_LDLIBS		:= -ldl -llog -lz -lGLESv2

LOCAL_STATIC_LIBRARIES := cpufeatures \
                          libFreeImage \
                          libzzip \

include $(BUILD_STATIC_LIBRARY)

$(call import-module,android/cpufeatures)